### ISSUE TITLE
Slows down loading huge solution file

### ISSUE THREAD

**Issue by unuunc** [fsprojects/VisualFSharpPowerTools#1037]
Hi ,

Can we disable the extension if project type is not of FSharp language projects. Observed that this extension slows down loading of my solutions file (very large, >100 projects ) even if that solution does not contain any Fsharp code.

I tried by enabling and disabling and it seems this extension is the root cause.

Thanks

**Comment by dungpa** [comment]
What features do you enable in the PowerTools setting? 

Only two features that do something while loading solutions are Task List comments and Folder Organization. Could you identify which feature causes the issue? Thanks.

**Comment by unuunc** [comment]
Tried your suggestion and it is faster after disabling these features. Still we can think of enabling extension only in case when project has FS code.

**Comment by vasily-kirichenko** [comment]
How much it's slower? 10x? 1.0001x?

**Comment by dungpa** [comment]
The extension doesn't do anything after knowing that the solution doesn't contain F# projects. However, checking  project types in solutions are expensive.

**Comment by xperiandri** [comment]
Maybe it is because of usage of old API? Could using EnvDTE90, 100 help?

**Comment by vasily-kirichenko** [comment]
@unuunc can you provide measurements? How longer your solution is loaded having VFPT enabled? If you cannot, I'll close this issue.

**Comment by 0x53A** [comment]
I have the same issue.
We have a solution with about 60 C# Projects, two C++ Projects and two F# Projects.

Without VFSPT, it loads in a few seconds (<10sec).
With VFSPT, it takes in the range of minutes.
(I don't have access to it at the moment, so can't measure it exactly).

What is annoying, is that changing the GIT branch triggers a (partial) solution reload, and waiting minutes after changing a branch takes a lot of the fun out of git.

I haven't had time for a detailed analysis, but one thing I noticed was that it spammed
[Language Service] Clearing FCS caches.
in the debug output.

**Comment by vasily-kirichenko** [comment]
Thanks a lot for the investigation. I suspect those three full synchronous GC collects are the problem. Will look at it.

**Comment by vasily-kirichenko** [comment]
@dsyme can you recommend a faster way to clean FCS caches (compared to `ClearLanguageServiceRootCachesAndCollectAndFinalizeAllTransients`)?

**Comment by vasily-kirichenko** [comment]
@0x53A Please try this VSIX https://ci.appveyor.com/project/dungpa/visualfsharppowertools/build/2.1.0-a1508090818/artifacts

I replaced `ClearLanguageServiceRootCachesAndCollectAndFinalizeAllTransients` with `InvalidateAll`.

**Comment by 0x53A** [comment]
@vasily-kirichenko looks good. In the same test (switching branches) it now doesn't slow down.
Thank you!

**Comment by vasily-kirichenko** [comment]
Great :) could you please keep an eye on VS memory consumption? Will it eats RAM indefinitely as you switching branches?

**Comment by 0x53A** [comment]
In a short test I couldn't find any leaks.

During the reload, memory spiked shortly (up to 800MB), but it always returned to a stable value (about 500MB) in a matter of seconds. Also, these are probably at least partially related to C# reparsing my files, not only F#.

So there seem to be at least no big leaks.

But I wouldn't expect there to be any, since the Clear only called the GC, which would run anyway if there was too much memory pressure.

**Comment by vasily-kirichenko** [comment]
Sounds good, thanks.

**Comment by vasily-kirichenko** [comment]
I've tested the fixed addin vs pure VS:

* Pure VS 2013:

load 1:25
reload #1 0:55 (0,65GB)
reload #2 0:55 (0,7GB)
reload #3 0:55 (0,75GB)

* Before the fix:

load 1:30
reload <infinite> (I waited for about 5 minutes for VS unfreezes and gave up)

* After the fix:

load 1:20
reload #1 1:10 (1,6GB)
reload #2 1:15 (1,7GB)
reload #3 1:20 (1,98GB)
reload #4 1:20 (1,89GB)

After four reloads VS starts freezing all the time, like this:

![image](https://cloud.githubusercontent.com/assets/873919/9154510/60569016-3e9b-11e5-8b6d-bcd728d21057.png)

and I had to close it since it was unusable.

**Comment by vasily-kirichenko** [comment]
I think we cannot do anything else with this.
