### ISSUE TITLE
Font coloring: bold setting not applied in VS2015

### ISSUE THREAD

**Issue by asik** [fsprojects/VisualFSharpPowerTools#1053]
In VS2015 Options -> Environment -> Fonts, checking the "bold" setting for an F# category like "F# Functions / Methods" has no effect. Changing the font color, however, does work.

**Comment by vasily-kirichenko** [comment]
I conform that:

* it is reproducible in VS 2015
* it is **not** reproducible in VS 2013

**Comment by dungpa** [comment]
AFAIK, persistence of font faces is handled automatically by Visual Studio. I wonder what we have to change at https://github.com/fsprojects/VisualFSharpPowerTools/blob/fc073522696b09d0f941cf4d0c30599c9fb910ef/src/FSharpVSPowerTools/SyntaxConstructClassifierProvider.cs#L291-L301 to make it work for VS 2015.

Could you give us some hints? /cc @jasonmalinowski @jaredpar @vladima

**Comment by jasonmalinowski** [comment]
In general, should update all of your classification formats to be Order After = <some appropriate default>. Right now since your ordering isn't correctly stated, all bets are off.

Still, it's odd that colors would work but bold wouldn't, so something else might be amiss. I'll e-mail a few people internally to try to get an answer. I'd mention them on GitHub but I don't know their handles.

**Comment by dungpa** [comment]
Oops, it works on master now after fixing ordering https://github.com/fsprojects/VisualFSharpPowerTools/pull/1064.

Case closed. Thank you for your insights.

**Comment by jasonmalinowski** [comment]
@dungpa: following back up, I chatted with a developer from the editor team to understand how we might have had a case where changing some options might work but not others. He described the algorithm as such:

1. get all the classifications for a span of text, in priority order
2. get the format definition for each one. Each format definition can specify just color, weight, or both.
3. for each format definition, go through them in color order and apply only the settings they specify.

So if the format you had in the UI checked bold, but some later format (since your ordering was all broken) then came around and specified weight without color, it'd override the setting. So that at least answers my question of "how can color work but bold doesn't" -- if there was a later setting, it can change one but not the other.

**Comment by dungpa** [comment]
@jasonmalinowski Thanks for the follow up. Your explanation makes perfect sense in the context of this bug.
