### ISSUE TITLE
XMLDoc comments unusably slow

### ISSUE THREAD

**Issue by dbwz8** [fsprojects/VisualFSharpPowerTools#1072]
When typing ///< it can literally take a minute or two before the comment insertion happens (typically it's more like several seconds). This is long enough to give up, go somewhere else in the file and then all of a sudden have the comment inserted completely at random. Very bad.

**Comment by vasily-kirichenko** [comment]
@dungpa We only parse current file here https://github.com/fsprojects/VisualFSharpPowerTools/blob/master/src/FSharpVSPowerTools.Core/XmlDocParser.fs#L141 It should be very fast. So, I suspect we are waiting in Checker queue until Parse and Check, triggered by other features, finishes. No idea what to do with it. /cc @dsyme

**Comment by dungpa** [comment]
@dbwz8 How big is the file that you observe the slow down? Does this happen right after opening a Visual Studio session (i.e. in the low traffic scenario)?

**Comment by dbwz8** [comment]
Here’s what we see:

 

1.    VS Just opened on a single small file… instantaneous

2.    VS Just opened with lots of tabs on a small file… instantaneous

3.    VS Just opened on a large file (3000 lines)… 10 seconds

4.    Doing the small file after the big file…. 5 seconds

5.    Doing the large file again… 20 seconds

 

It definitely gets worse the longer you’re in VS, however sometimes it’s instantaneous even after long editing sessions on large files. Very unpredictable.

**Comment by dungpa** [comment]
@dbwz8 Apologize for the slow reply.

Could you try a recent build with a potential fix for the issue https://ci.appveyor.com/project/dungpa/visualfsharppowertools/build/2.2.0-a1510171153? 

Due to historical reasons, XmlDoc generation wasn't cached properly as other features. It has been corrected in https://github.com/fsprojects/VisualFSharpPowerTools/pull/1173 and https://github.com/fsprojects/VisualFSharpPowerTools/pull/1177.

Thank you.

**Comment by vasily-kirichenko** [comment]
@dbwz8 If you still experience any issues with XML Doc generation, reopen this issue or create another one.
