### ISSUE TITLE
Go To Definition from signature file

### ISSUE THREAD

**Issue by jackfoxy** [fsprojects/VisualFSharpPowerTools#1120]
Go To Definition bypasses the signature file definition and goes to the function or value definition in the underlying code file, which I agree is a good solution.

If you are in the signature file, however, and select Go To Definition for some item defined there, it stays in that file and does not take you to the underlying definition.

**Comment by dungpa** [comment]
Hi Jack,

If the signature file is present, Go To Definition is handled by Visual F# Tools. I think it is by design that Go To Definition on signature files stays in the files.

There is a relevant UserVoice entry to vote for http://vfpt.uservoice.com/forums/247560-general/suggestions/6920300-go-to-implementation-command-to-go-from-fsi-to-f

If you would like to change the default behaviour of Go To Definition in this case, please open an issue at  https://github.com/Microsoft/visualfsharp
