### ISSUE TITLE
FCS does not return symbol for a class which has become module

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/VisualFSharpPowerTools#1174]
`DepthParser` was a class in different project, I made it a module. Now no way to force FCS to return a symbol for it:

![1](https://cloud.githubusercontent.com/assets/873919/10513637/9ba0cbec-7351-11e5-981f-a156b1b4b176.gif)

Closing/opening the file does not help either.

**Comment by vasily-kirichenko** [comment]
As we don't recheck projects anymore we should somehow invalidate FCS if any of dependent projects has been rebuilt.

**Comment by vasily-kirichenko** [comment]
I believe there was this functionality. Cannot find now.

**Comment by dungpa** [comment]
You mean this https://github.com/fsprojects/VisualFSharpPowerTools/blob/0fc4314320fb97cdad9249da1bf3fe21eaafb160/src/FSharpVSPowerTools.Logic/SyntaxConstructClassifier.fs#L345-L354?

I think the problem is that the referenced project is still in cache https://github.com/fsprojects/VisualFSharpPowerTools/blob/0fc4314320fb97cdad9249da1bf3fe21eaafb160/src/FSharpVSPowerTools.Logic/ProjectFactory.fs#L75. It should be invalidated when we force coloring.

**Comment by vasily-kirichenko** [comment]
Should we also call `FSharpChecker.InvalidateConfiguration` for the current project?

**Comment by vasily-kirichenko** [comment]
And not only coloring not work, all features do not.

**Comment by vasily-kirichenko** [comment]
I don't think `ProjectProvider` cache should be invalidated because the project is not changed.

**Comment by vasily-kirichenko** [comment]
We should 
1. tell FCS to invalidate its caches for the project that was built 
2. notify colorizer and Highlight references tagger

**Comment by vasily-kirichenko** [comment]
However, doesn't FCS checks if assemblies has changed? If so, then it should already work as expected :(

**Comment by vasily-kirichenko** [comment]
On a minimal solution everything work ok.

**Comment by vasily-kirichenko** [comment]
We've reverted starting background compilation and this issue has disappear.
