### ISSUE TITLE
[Outlining] Tooltips contain extra end line characters

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/VisualFSharpPowerTools#1180]
VS 2013

![image](https://cloud.githubusercontent.com/assets/873919/10561030/ea0f0660-7525-11e5-9f41-b24759780d3d.png)

**Comment by cloudRoutine** [comment]
Using build [2.2.0-a1510171942](https://ci.appveyor.com/project/dungpa/visualfsharppowertools/build/2.2.0-a1510171942) in VS 2013 my hint tooltip looks like

![](http://i.imgur.com/z6YcNg4.png)

It looks like your screenshot is from the experimental instance, this is the issue I told you about earlier today.

**Comment by vasily-kirichenko** [comment]
No, it is from normal instance.

**Comment by cloudRoutine** [comment]
The issue was I didn't account for the different possible linebreak characters.
Should be fixed in #1182 , tested in VS2013 & VS2015

### VS 2013 `\r\n`
![](http://i.imgur.com/41NQp6h.png)

### VS 2013 `\n`
![](http://i.imgur.com/VECce9b.png)

### VS 2015 `\r\n`
![](http://i.imgur.com/kIUoyTH.png)

### VS 2015 `\n`
![](http://i.imgur.com/c1TIg3K.png)

**Comment by vasily-kirichenko** [comment]
Fixed in https://github.com/fsprojects/VisualFSharpPowerTools/pull/1182
