### ISSUE TITLE
[Outlining] `match` folded twice

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/VisualFSharpPowerTools#1188]
![6677](https://github-cloud.s3.amazonaws.com/assets/873919/10565550/be086e6a-75db-11e5-8d58-0bfb95462285.gif)

**Comment by cloudRoutine** [comment]
Match is folding twice because it's the clause of another pattern match and has a foldable scope underneath it. If clauses used the `Below` style of folding ( `...` ) it wouldn't be an issue in this case, but it'd still be a problem if the match were on the same line as the start of the guard.  This double folding issue can appear in a few other places, but I'm not sure what the general strategy should be to address it yet.

**Comment by cloudRoutine** [comment]
C# has the same problem

![double-collapse](https://cloud.githubusercontent.com/assets/680051/10625566/7414f9fc-7772-11e5-8296-4b36800a5636.gif)

**Comment by vasily-kirichenko** [comment]
Ok.
