### ISSUE TITLE
Lint settings on multi project solution (C#/F# etc)

### ISSUE THREAD

**Issue by xenocons** [fsprojects/VisualFSharpPowerTools#1251]
Hi,

For some reason on my solution the F# Power Tools option for Lint says 'No projects are currently open'. When I create a new F# solution with just 1 project, the options appear fine. 

My current solution has C#, F# and SQL.

**Comment by dungpa** [comment]
@duckmatt When will the textblock at https://github.com/fsprojects/VisualFSharpPowerTools/blob/8c39b65de36beac46732d8e7ddde658ca985b385/src/FSharpVSPowerTools.Logic/LintOptionsPageControl.xaml#L25-L38 get overwritten by configs? I have a hard time connecting this with the code behind. Just wanna investigate this issue further. Thanks.

**Comment by duckmatt** [comment]
That will be collapsed when [`LoadedConfig`](https://github.com/fsprojects/VisualFSharpPowerTools/blob/8c39b65de36beac46732d8e7ddde658ca985b385/src/FSharpVSPowerTools.Logic/Linting/OptionsViewModel.fs#L235) is set to true, whether it's true or not is based upon whether [this is `Some(_) or None`](https://github.com/fsprojects/VisualFSharpPowerTools/blob/8c39b65de36beac46732d8e7ddde658ca985b385/src/FSharpVSPowerTools.Logic/Linting/LintOptionsPage.fs#L92). The functions from FSharpLint that are used are [in the `Configuration.Management` module](https://github.com/fsprojects/FSharpLint/blob/f0e0193a59055484e1a64bad6e641c9d1584321f/src/FSharpLint.Framework/Configuration.fs#L490). Having a quick skim I can't see anything immediately obvious and am unable to recreate the bug but it looks like [`updateLoadedConfigs`](https://github.com/fsprojects/VisualFSharpPowerTools/blob/fbcb4f0a4d044f2b959e06ac605039c9cb163d19/src/FSharpVSPowerTools.Logic/Linting/LintOptionsPage.fs#L89) could be returning an empty sequence

**Comment by dungpa** [comment]
@duckmatt Can you explain a bit what's going on in configuration management? AFAIK FSharpLint looks for configuration files in each project folder and uses configs in sub-folders to override those in parent folders. If there are no such config files, a config file for the whole solution is used. We haven't supported lint options for independent F# scripts, which are a bit unfortunate. 

Is there any way to retrofit lint options for script files in the current model supporting projects and solutions?

**Comment by duckmatt** [comment]
@dungpa There's nothing that inherently ties it to projects - the configs are per directory in a path. When a path is [added](https://github.com/fsprojects/FSharpLint/blob/f0e0193a59055484e1a64bad6e641c9d1584321f/src/FSharpLint.Framework/Configuration.fs#L520), all of its ancestor directories will also be added, so if we added `C:\X\Y`, it would try loading the configuration files for `C:\X\Y`, `C:\X`, and `C:\`. 

When we run the linter it needs a full configuration and the configuration files in any directory could be partially complete, so what happens is that it [folds over](https://github.com/fsprojects/FSharpLint/blob/f0e0193a59055484e1a64bad6e641c9d1584321f/src/FSharpLint.Framework/Configuration.fs#L639) all the directories for a path, it starts with an initial state of the default configuration that is a part of the lint assembly so that we are always guaranteed a full configuration. This approach means that a configuration file will override a configuration in a parent directory.

It seems like it may not need much work to support script files, possibly just needs to add the path of the directory containing the file. I could try taking a look at adding this when I find a bit of time

**Comment by dungpa** [comment]
@xenocons Do you have projects in nested folders. If so, I made a fix at https://ci.appveyor.com/project/dungpa/visualfsharppowertools/build/2.2.0-a1511182205/artifacts, please give it a try.

@duckmatt That would be great. Supporting Lint options on fsx files is an important enhancement.

**Comment by xenocons** [comment]
@dungpa yes, I do have projects in nested folders. I have tested using the latest posted, and it works!

**Comment by vasily-kirichenko** [comment]
:+1:
