### ISSUE TITLE
F# Power Tools color scheme does not adjust when Visual Studio color scheme is changed

### ISSUE THREAD

**Issue by surban** [fsprojects/VisualFSharpPowerTools#1359]
### Description

F# Power Tools color scheme does not adjust when Visual Studio color scheme is changed.

### Repro steps

Please provide the steps required to reproduce the problem

1. Uninstall F# Power Tools.
2. Set Visual Studio color theme to blue.
3. Install F# Power Tools.
4. Set Visual Studio color theme to dark.

### Expected behavior

F# Power Tools color scheme adjusts to match Visual Studio color scheme.

### Actual behavior

F# Power Tools color scheme does not adjust, making many words unreadable (see screenshot).

![image](https://cloud.githubusercontent.com/assets/1213857/14298024/db95af6a-fb82-11e5-924e-711048c012e1.png)

### Known workarounds

Uninstall, then reinstall the extension. (disable, then enable, does not help)

### Related information 

* Operating system: Windows 10 Insider Preview
* Branch: Version 2.3.0 on Visual Studio 2015 Update 1

**Comment by dungpa** [comment]
@jasonmalinowski Could you give some hints on fixing this issue?

Here is a summary:

 - When VFPT starts inside VS, we initialize format properties with appropriate colors https://github.com/fsprojects/VisualFSharpPowerTools/blob/60356156a9afd625d2076a990f081bcb28cab458/src/FSharpVSPowerTools/Commands/SymbolClassifiersProvider.cs#L228
 - When there is a ThemeChanged event and the new theme is different from current one, we update all our format properties https://github.com/fsprojects/VisualFSharpPowerTools/blob/60356156a9afd625d2076a990f081bcb28cab458/src/FSharpVSPowerTools/Commands/SymbolClassifiersProvider.cs#L170-L211.

It seems to work fine for normal scenarios e.g. installing VFPT, restarting VS, changing themes. The bug here occurs when installing VFPT, and then changing themes without actually restarting VS. Why restarting VS in between makes the bug go away? What are we missing?

Thank you.

**Comment by jasonmalinowski** [comment]
I really have no clue how the theme stuff works. @olegtk might know more?

**Comment by dungpa** [comment]
@olegtk Could you have a look?

Here is another repro case for the bug https://github.com/fsprojects/VisualFSharpPowerTools/issues/1128#issuecomment-184085561

**Comment by OkayX6** [comment]
(how do you know all these people?? :))

**Comment by olegtk** [comment]
We don't really support well the scenario when you install an extension and start using it right away without restarting VS. That's why "You must restart Microsoft Visual Studio in order for the changes to take effect" message in Extensions and Updates dialog.

**Comment by dungpa** [comment]
@olegtk Thank you for the answer.

I would expect that color would be in sync after VS restart. But it seems changing themes right after extension install leaves colors in a wrong state. 

Where do editor colors persist? Do you have any suggestion to handle color theme change in a more robust way (e.g. using pkgdef files)?

**Comment by olegtk** [comment]
I'm not sure what are you trying to solve, sorry. You have to restart VS after installing an extension, otherwise it's not guaranteed to work correctly.
According to @dungpa:

> It seems to work fine for normal scenarios e.g. installing VFPT, restarting VS, and then changing themes.

**Comment by hmemcpy** [comment]
Yes, looks like this bug affects functions/methods and operators highlighting. Not so sure why yet. I'm trying to look into it.
It definitely is not related to Depth colorization, I am able to reproduce this bug with depth colorization disabled.

**Comment by surban** [comment]
Even if I restart VS after installing the extension and/or changing the color theme, the colors are not updated correctly.

**Comment by surban** [comment]
Is there any config file or registry setting that I could delete to force F# Power Tools to adopt the new Visual Studio color scheme without having to reinstall?
