### ISSUE TITLE
Format document produces unnecessary trailing whitespaces

### ISSUE THREAD

**Issue by xperiandri** [fsprojects/VisualFSharpPowerTools#1382]
### Description

Execution of "Format Document" command produces unnecessary trailing whitespaces

<img width="757" alt="trailing whitespaces" src="https://cloud.githubusercontent.com/assets/2365592/15092502/92830218-1474-11e6-9d20-8de292ee2186.png">

### Repro steps
1. Install [Trailing Whitespace Visualizer](https://visualstudiogallery.msdn.microsoft.com/a204e29b-1778-4dae-affd-209bea658a59) extension
2. Execute "Format Document" command

### Expected behavior

No additional trailing whitespaces added

### Actual behavior

Before the function on the empty line added whitespaces for indentation.
After `=` sign and `then` and `else` key words added whitespace even though the line has no other characters after.

### Related information 

* Extension version 2.4.1
* Visual Studio 2015 Update 2
* Other extensions installed in Visual Studio - does not matter for this issue

**Comment by vasily-kirichenko** [comment]
Why this is a problem?

**Comment by smoothdeveloper** [comment]
@vaskir some people don't like trailing invisible char, and using a formatting tool you'd expect the output to be closest to optimal format (disregarding aesthetics).

Also those trailing characters tend to create unnecessary churn during the life of files because some will get added/removed often unknowingly.

Many people or even editors have default settings stripping those out.

**Comment by vasily-kirichenko** [comment]
Report it to Fantomas repository.
