### ISSUE TITLE
Adding Travis CI

### ISSUE THREAD

**Issue by smoothdeveloper** [fsprojects/VisualFSharpPowerTools#1417]
Core project is published as a nuget and used by some projects (FSharp.Formatting), I believe we should start running compilation and tests under Travis continuous integration.

**Comment by cloudRoutine** [comment]
If you want to setup it up and handle dealing with all of the headaches, by all means go for it.

**Comment by smoothdeveloper** [comment]
How does it work, I try to set it up on my fork? I've never setup travis.

**Comment by cloudRoutine** [comment]
Yea you can set it up on your fork, you need an account with them and it should let you add tracking to repo on their side. They have some guides on their site, you can look at other projects that are using it for CI to see how their build configs are setup. It'll probably need to be more involved than theirs since Core and tests on Core are all that should be run on it.
