### ISSUE TITLE
Comment Highlighting

### ISSUE THREAD

**Issue by Hosch250** [fsprojects/VisualFSharpPowerTools#1492]
### Description

Sometimes I'll use a `todo` or `bug` comment to mark something that isn't completed while I work on something else.  It would be nice to have a Resharper-style highlight of the comment.

### Expected behavior

This should match comments either with a literal or regex match, and the user should be able to specify the literal match, how to match it, and the font color for the comment.  R#'s version changes the color for and bolds the entire comment block, but I find that difficult to read, so perhaps it could just set the color and font weight for the matched text?

**Comment by smoothdeveloper** [comment]
@Hosch250 it is a good suggestion, I'm also wondering if you could log it as an issue on https://youtrack.jetbrains.com/ because it feels jetbrains could implement that small bit of support quite easily in their tool too.

If it is something you'd like to take a look at, I gather it wouldn't be too difficult to parse all comments using the untyped AST to get the ranges of text you are interested in.

**Comment by vasily-kirichenko** [comment]
This project is deprecated, all bug fixes and feature requests should be posted to VFT repository.

About comments, unfortunately parser AST does not include comments.
