### ISSUE TITLE
Format Code removed essential parenthesis

### ISSUE THREAD

**Issue by matthid** [fsprojects/VisualFSharpPowerTools#366]
When you have code like:

    type A =
        abstract member M : int -> (int -> unit)
        abstract member M : float -> int

the parenthesis around (int -> unit) are actually important, because after formatting you get

    type A = 
        abstract M : int -> int -> unit
        abstract M : float -> int

Which results in a compiler error (FS0439). (In fact you first get weird compiler errors in the implementations). Can I somehow disable this as a workaround?

**Comment by dungpa** [comment]
@matthid My apologies for answering way too late (Well, it has been more than a year).

I did multiple tries to fix this bug in the past but fail. At one point, I believed that the AST lacked relevant information to preserve parentheses. I figured out a non-intrusive way to fix the bug today.

The bug has been fixed in https://github.com/dungpa/fantomas/pull/177 and the fix flows to VFPT at https://github.com/fsprojects/VisualFSharpPowerTools/pull/1115.

**Comment by matthid** [comment]
No need to be sorry. I'm glad this will be fixed now :+1: 
I remember this issue was one of the blockers for me to use "Format Code on Save" with F# (which is a good way to find such bugs apparently). So maybe with 2.1.0 its time to try again :)
