### ISSUE TITLE
Almost nothing works for a code using Fleece 

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/VisualFSharpPowerTools#444]
```fsharp
module FleeceTest.Test

#r @"..\packages\System.Json.4.0.20126.16343\lib\net40\System.Json.dll"
#r @"..\packages\ReadOnlyCollectionInterfaces.1.0.0\lib\NET45\ReadOnlyCollectionsInterfaces.dll"
#r @"..\packages\Fleece.0.2.0\lib\NET40\Fleece.dll"

open Fleece

type T() =
   static member FromJSON (_: int) = function
       | JObject o -> printfn "%A" o 
       | _ -> ()
```
FCS does not return anything for line `| JObject o -> printfn "%A" o`.

**Comment by vasily-kirichenko** [comment]
@dungpa no, it has not been fixed. VS 2013:

![image](https://cloud.githubusercontent.com/assets/873919/9025347/e2857de6-3909-11e5-857e-67de16a79339.png)

No coloring, no current symbol highlighting and so on.

**Comment by dungpa** [comment]
This version works (notice changine 'NET45' to 'Net40-client'):

```fsharp
module FleeceTest.Test

#r @"..\packages\System.Json.4.0.20126.16343\lib\net40\System.Json.dll"
#r @"..\packages\ReadOnlyCollectionInterfaces.1.0.0\lib\Net40-client\ReadOnlyCollectionsInterfaces.dll"
#r @"..\packages\Fleece.0.2.0\lib\NET40\Fleece.dll"

open Fleece

type T() =
   static member FromJSON (_: int) = function
       | JObject o -> printfn "%A" o 
       | _ -> ()
```
I guess the reason is that FSI still uses .NET 4.0 assemblies for resolution.

Here is the resolution with project files. It works fine since all assemblies are resolved in .NET 4.5:

> GetProjectCheckerOptions: ProjectFileName: C:\Users\abc\Documents\Visual Studio 2013\Projects\TutorialPerf1\TutorialPerf1.fsproj, ProjectFileNames: [|"C:\Users\abc\AppData\Local\Temp\.NETFramework,Version=v4.5.AssemblyAttributes.fs";
  "C:\Users\abc\Documents\Visual Studio 2013\Projects\TutorialPerf1\Library1.fs"|], FSharpProjectOptions: [|"-o:obj\Debug\TutorialPerf1.dll"; "-g"; "--debug:full"; "--noframework";
  "--define:DEBUG"; "--define:TRACE"; "--doc:bin\Debug\TutorialPerf1.XML";
  "--optimize-"; "--tailcalls-";
  "-r:C:\Users\abc\Documents\Visual Studio 2013\Projects\TutorialPerf1\packages\Fleece.0.2.0\lib\NET40\Fleece.dll";
  "-r:C:\Users\abc\Documents\Visual Studio 2013\Projects\TutorialPerf1\packages\FsControl.1.0.8\lib\net40\FsControl.Core.dll";
  "-r:C:\Program Files (x86)\Reference Assemblies\Microsoft\FSharp\.NETFramework\v4.0\4.3.1.0\FSharp.Core.dll";
  "-r:C:\Users\abc\Documents\Visual Studio 2013\Projects\TutorialPerf1\packages\FSharp.Data.2.0.8\lib\net40\FSharp.Data.dll";
  "-r:C:\Users\abc\Documents\Visual Studio 2013\Projects\TutorialPerf1\packages\FSharpPlus.0.0.3\lib\net40\FSharpPlus.dll";
  "-r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\mscorlib.dll";
  "-r:C:\Users\abc\Documents\Visual Studio 2013\Projects\TutorialPerf1\packages\ReadOnlyCollectionExtensions.1.0.0\lib\NET45\ReadOnlyCollectionsExtensions.dll";
  "-r:C:\Users\abc\Documents\Visual Studio 2013\Projects\TutorialPerf1\packages\ReadOnlyCollectionInterfaces.1.0.0\lib\NET45\ReadOnlyCollectionsInterfaces.dll";
  "-r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Core.dll";
  "-r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.dll";
  "-r:C:\Users\abc\Documents\Visual Studio 2013\Projects\TutorialPerf1\packages\System.Json.4.0.20126.16343\lib\net40\System.Json.dll";
  "-r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Numerics.dll";
  "-r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Xml.Linq.dll";
  "--target:library"; "--warn:3"; "--warnaserror:76"; "--vserrors";
  "--validate-type-providers"; "--LCID:1033"; "--utf8output"; "--fullpaths";
  "--flaterrors"; "--subsystemversion:6.00"; "--highentropyva+";
  "--sqmsessionguid:8fa118b2-3de4-48c9-918f-411d6aeaa69e"|], IsIncompleteTypeCheckEnvironment: false, UseScriptResolutionRules: false, ReferencedProjects: [||]
Parsing: Trigger parse (fileName=C:\Users\abc\Documents\Visual Studio 2013\Projects\TutorialPerf1\Library1.fs)

**Comment by vasily-kirichenko** [comment]
I confirm, it work. Thanks!
