### ISSUE TITLE
Feature Request - FSI Window Transparency

### ISSUE THREAD

**Issue by xenocons** [fsprojects/VisualFSharpPowerTools#937]
Hello,

It would be nice to have a transparent FSI window so you can still see the source code behind FSI.

http://stackoverflow.com/questions/3945242/visual-studio-2010-semi-transparent-floating-windows explains how to get the windows (once of which should be 'F# Interactive') then it should be a matter of just pinvoking https://msdn.microsoft.com/en-us/library/ms633540(v=vs.85).aspx with the hwnd to set the transparency.

Edit: Just had a look with spy++, it looks like perhaps the window for FSI that visual studio creates is not setting WS_EX_LAYERED, which means that it might not be possible...

**Comment by vasily-kirichenko** [comment]
1. We manage suggestions and feature requests here: http://vfpt.uservoice.com/
2. You should consider to suggest this feature in Visual F# Tools repo/user voice, here: https://github.com/Microsoft/visualfsharp and here http://fslang.uservoice.com/ because we don't touch FSI window and it's unlikely we will do.

**Comment by xenocons** [comment]
Ok, noted, I will go add the suggestion to those pages.
