### ISSUE TITLE
No syntax coloring when using dark theme

### ISSUE THREAD

**Issue by torbonde** [fsprojects/VisualFSharpPowerTools#939]
I'm using VS2012, and I don't get any syntax coloring when I use the dark theme. Well, apart from the type/let/with/etc. being blue and strings being orange. If I switch to the light or blue theme, there are no problems.

Before I installed VS2012, I installed VS2013 Community Edition, but had to uninstall it again, since it kept crashing. I don't know if this could have anything to do with it?

**Comment by OkayX6** [comment]
Weird. Which version of VFPT do you have?

**Comment by torbonde** [comment]
1.7.2 it seems. For some reason, VS complains about the underlying connection being closed, when I try to update.:/

**Comment by dungpa** [comment]
Just debug this today. VS2012 seems to behave differently in terms of ordering.

Coloring is rendered if I remove these lines:
https://github.com/fsprojects/VisualFSharpPowerTools/blob/b004049d0aea62232f05e4d328e2906480dabbb7/src/FSharpVSPowerTools/SyntaxConstructClassifierProvider.cs#L236

Any idea that I can set different attribute values on different VS versions? I really don't want to branch out the extension due to this bug.

/cc @OkayX6 @vasily-kirichenko

**Comment by OkayX6** [comment]
Why is only different with the dark theme?
Also, maybe you could make a custom attribute inheriting from Order, with different execution path depending on the version of VS?

**Comment by dungpa** [comment]
@OkayX6 Coloring disappears completely on dark theme in VS 2012. It works partially in VS 2012 light theme (Printf & escaped characters aren't shown). I have no idea why.

Unfortunately `OrderAttribute` is a sealed class so I can't alter its behaviour.

**Comment by dungpa** [comment]
@torbonde Would you mind to check whether this v1.7.4 fixes the issue https://ci.appveyor.com/project/dungpa/visualfsharppowertools/build/1.8.0-a1503191323/artifacts? Thanks.

**Comment by torbonde** [comment]
@dungpa It does indeed fix the issue. Thanks!
