### ISSUE TITLE
Renaming a file in a folder leads to confusing behavior

### ISSUE THREAD

**Issue by exercitusvir** [fsprojects/VisualFSharpPowerTools#974]
When I rename a file in a folder, the renamed file jumps to the top of the project out of the folder. Then when I move the file with the Alt+Up/Down shortcut, it jumps back down into the folder. So it appears Visual F# Power Tools knows where it should be, but somehow Visual Studio visualizes it at the wrong position.

**Comment by dungpa** [comment]
We documented the behaviour at http://fsprojects.github.io/VisualFSharpPowerTools/folderorganization.html#Limitations.

It's a bug in Visual F# Tools' project system. Unfortunately, there is nothing we can do from our extension.

I reported it some time ago https://github.com/Microsoft/visualfsharp/issues/259. It has been fixed in Visual F# Tools 4.0 for VS 2015 RC. In general, experience in folder organization will be improved in VS 2015; you should check it out.

**Comment by dungpa** [comment]
Closing since it's being fixed upstream.
