### ISSUE TITLE
Support for Matlab-like code blocks in the editor

### ISSUE THREAD

**Issue by vadimkantorov** [fsprojects/VisualFSharpPowerTools#976]
Matlab supports code blocks which are very useful for the interactive mode. Code blocks are areas of code between some separators (in Matlab separators are lines starting with double comment character, %%). All code in a code block under the cursor can be executed with a single keystroke.

**Comment by dungpa** [comment]
Hi Vadim,

We've got the feature request at http://vfpt.uservoice.com/forums/247560-general/suggestions/6532884-send-code-cell-to-fsi-using-key-combination.
It's a very useful one. I hope a contributor will pick it up and send PR. 

Since we handle feature requests on UserVoice, I'll close it here.

Thanks.
